Vagrant.configure("2") do |config|
  # Налаштування першої машини web1
  config.vm.define "web1" do |web1|
    web1.vm.box = "bento/ubuntu-20.04"
    web1.vm.network "private_network", ip: "192.168.50.4"
    web1.vm.provider "parallels" do |prl|
      prl.memory = 2048
      prl.cpus = 2
    end
    web1.vm.hostname = "web1"
  end

  # Налаштування другої машини web2
  config.vm.define "web2" do |web2|
    web2.vm.box = "bento/ubuntu-20.04"
    web2.vm.network "private_network", ip: "192.168.50.5"
    web2.vm.provider "parallels" do |prl|
      prl.memory = 2048
      prl.cpus = 2
    end
    web2.vm.hostname = "web2"
  end

  # Налаштування третьої машини db
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-20.04"
    db.vm.network "private_network", ip: "192.168.50.6"
    db.vm.provider "parallels" do |prl|
      prl.memory = 4096
      prl.cpus = 4
    end
    db.vm.hostname = "db"
  end

  # Збільшення часу очікування для завантаження
  config.vm.boot_timeout = 600
end
